// @review [x]
pub mod blob;
pub mod primary;
pub mod relational;
pub mod secondary;
pub mod subscription;

use crate::traits::structural::database::tables::codec::StoreValue;
use crate::traits::structural::database::tables::core::{
    NodeStorageMode, TableKey, TableStorageMode,
};
use crate::traits::structural::schema::{
    definitions::NetabaseDefinition,
    models::{
        NetabaseModelWithKeys,
        keys::{
            blob::BlobKeysEnum,
            primary::PrimaryKey,
            relational::RelationalKeysEnum,
            secondary::SecondaryKeysEnum,
            subscription::SubscriptionKeysEnum,
        },
    },
    repositories::NetabaseRepository,
};

pub trait NetabaseModelKeys<
    R: NetabaseRepository,
    D: NetabaseDefinition<R>,
    M: NetabaseModelWithKeys<R, D>,
> where
    Self: strum::IntoDiscriminant,
{
    type PrimaryKey: PrimaryKey<R, D, M>;
    type SecondaryKeys: SecondaryKeysEnum<R, D, M>;
    type RelationalKeys: RelationalKeysEnum<R, D, M>;
    type SubscriptionKeys: SubscriptionKeysEnum<R, M>;
    type BlobKeys: BlobKeysEnum<R, D, M>;
}

// NOTE: The definition/repository aggregation enums named in the (now-removed) #tree_keys
// TODOs ARE generated by the macro pipeline: see definition_generator.rs (Secondary/
// Relational/Blob/SubscriptionKeys, wired into NetabaseDefinitionKeys) and the
// repository_generator.rs mirror. The PrimaryKey aggregation enums are likewise generated.

pub trait GroupedEnumKey: TableKey {}
impl<T: TableKey> GroupedEnumKey for T {}

pub trait GroupedEnumValue: StoreValue {}
impl<T: StoreValue> GroupedEnumValue for T {}

pub trait ModelKeysStorageMode<
    R: NetabaseRepository,
    D: NetabaseDefinition<R>,
    M: NetabaseModelWithKeys<R, D>,
>: NodeStorageMode
{
    const PRIMARY_MODE: TableStorageMode = TableStorageMode::Linear;
    const SECONDARY_MODE: TableStorageMode = TableStorageMode::Sharded;
    const RELATIONAL_MODE: TableStorageMode = TableStorageMode::Sharded;
    const SUBSCRIPTION_MODE: TableStorageMode = TableStorageMode::Sharded;
    const BLOB_MODE: TableStorageMode = TableStorageMode::Sharded;
}

pub trait NetabaseDefinitionKeys<R: NetabaseRepository, D: NetabaseDefinition<R>> {
    type PrimaryKey: TableKey;
    type SecondaryKeys: DefinitionSecondaryKeys<R, D>;
    type RelationalKeys: DefinitionRelationalKeys<R, D>;
    type BlobKeys: DefinitionBlobKeys<R, D>;
    type SubscriptionKeys: DefinitionSubscriptionKeys<R, D>;
}
pub trait NetabaseRepositoryKeys<R: NetabaseRepository> {
    type PrimaryKey: TableKey;
    type SecondaryKeys: RepositorySecondaryKeys<R>;
    type RelationalKeys: RepositoryRelationalKeys<R>;
    type BlobKeys: RepositoryBlobKeys<R>;
    type SubscriptionKeys: RepositorySubscriptionKeys<R>;
}

pub trait DefinitionSecondaryKeys<R: NetabaseRepository, D: NetabaseDefinition<R>>: TableKey
{
}
pub trait RepositorySecondaryKeys<R: NetabaseRepository>: TableKey
{
}

pub trait DefinitionRelationalKeys<R: NetabaseRepository, D: NetabaseDefinition<R>>: TableKey
{
}
pub trait RepositoryRelationalKeys<R: NetabaseRepository>: TableKey
{
}

pub trait DefinitionSubscriptionKeys<R: NetabaseRepository, D: NetabaseDefinition<R>>: TableKey
{
}
pub trait RepositorySubscriptionKeys<R: NetabaseRepository>: TableKey
{
}

pub trait DefinitionBlobKeys<R: NetabaseRepository, D: NetabaseDefinition<R>>: TableKey
{
}
pub trait RepositoryBlobKeys<R: NetabaseRepository>: TableKey
{
}
