[package]
name = "netabase_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits", "visit"] }
quote = "1.0"
proc-macro2 = "1.0"
proc_macro_flow_core = { git = "ssh://git@github.com/nzuzo-magagula/proc_macro_flow.git", branch = "core" }
proc_macro_flow_macros = { git = "ssh://git@github.com/nzuzo-magagula/proc_macro_flow.git", branch = "core" }
strum = "0.28"

[dev-dependencies]
trybuild = "1.0"
netabase_store = { path = "../netabase_store" }
netabase_arena = { path = "../netabase_arena" }
rkyv = { version = "0.8.16", features = ["unaligned"] }
