pub mod model_blob;

/// Default chunk size (in bytes) used by the `whole` blob strategy when splitting a serialized
/// value into [`Blobbable::Chunk`]s. Centralized here (rather than hardcoded in the macro) so the
/// `whole`-strategy chunking granularity is tunable in one place. A per-type override via the
/// `#[blob(chunk_size = N)]` attribute is a future addition.
pub const DEFAULT_BLOB_CHUNK_SIZE: usize = 1024;

/// A trait indicating that a type represents a chunk of a Blobbable item.
/// The macro will generate types that implement this trait. Chunks are
/// variable-size and travel as raw bytes at the storage layer (std-only),
/// so they are deliberately NOT `StoreValue`/`TableValue`.
pub trait BlobChunk: 'static {}

/// The base trait for items that can be broken down into, and reconstructed from, blob chunks.
pub trait Blobbable: Sized {
    /// The specific chunk type generated by the macro for this struct or enum.
    /// - For Field-Level Blobbing: An Enum.
    /// - For Whole-Item Chunking: A Newtype Tuple Struct.
    type Chunk: BlobChunk;

    /// Break the item into a collection of its chunks.
    fn to_chunks(&self) -> Vec<Self::Chunk>;

    /// Reconstruct the item from a collection of its chunks.
    fn from_chunks(chunks: Vec<Self::Chunk>) -> Self;
}

/// Strategy 1: Field-Level Blobbing
/// The macro generates an enum of the struct fields (or nested enum fields) to hold byte arrays.
/// This provides a typesafe way to interact with partially constructed opaque data types.
pub trait FieldBlobbable: Blobbable {}

/// Strategy 2: Whole-Item Chunking
/// The item is serialized, broken into chunks, and wrapped in a generated newtype struct.
pub trait ChunkBlobbable: Blobbable + TryInto<Vec<u8>> + TryFrom<Vec<u8>> {}

// Blanket implementations for common types
impl BlobChunk for Vec<u8> {}
impl Blobbable for Vec<u8> {
    type Chunk = Vec<u8>;
    fn to_chunks(&self) -> Vec<Self::Chunk> {
        vec![self.clone()]
    }
    fn from_chunks(chunks: Vec<Self::Chunk>) -> Self {
        chunks.into_iter().flatten().collect()
    }
}

impl BlobChunk for String {}
impl Blobbable for String {
    type Chunk = String;
    fn to_chunks(&self) -> Vec<Self::Chunk> {
        vec![self.clone()]
    }
    fn from_chunks(chunks: Vec<Self::Chunk>) -> Self {
        chunks.into_iter().collect()
    }
}

impl BlobChunk for u64 {}
impl BlobChunk for u128 {}
impl Blobbable for u128 {
    type Chunk = u128;
    fn to_chunks(&self) -> Vec<Self::Chunk> {
        vec![*self]
    }
    fn from_chunks(chunks: Vec<Self::Chunk>) -> Self {
        chunks.into_iter().next().unwrap_or(0)
    }
}
impl Blobbable for u64 {
    type Chunk = u64;
    fn to_chunks(&self) -> Vec<Self::Chunk> {
        vec![*self]
    }
    fn from_chunks(chunks: Vec<Self::Chunk>) -> Self {
        chunks.into_iter().next().unwrap_or(0)
    }
}

impl BlobChunk for u32 {}
impl Blobbable for u32 {
    type Chunk = u32;
    fn to_chunks(&self) -> Vec<Self::Chunk> {
        vec![*self]
    }
    fn from_chunks(chunks: Vec<Self::Chunk>) -> Self {
        chunks.into_iter().next().unwrap_or(0)
    }
}

impl BlobChunk for i64 {}
impl Blobbable for i64 {
    type Chunk = i64;
    fn to_chunks(&self) -> Vec<Self::Chunk> {
        vec![*self]
    }
    fn from_chunks(chunks: Vec<Self::Chunk>) -> Self {
        chunks.into_iter().next().unwrap_or(0)
    }
}

impl BlobChunk for i32 {}
impl Blobbable for i32 {
    type Chunk = i32;
    fn to_chunks(&self) -> Vec<Self::Chunk> {
        vec![*self]
    }
    fn from_chunks(chunks: Vec<Self::Chunk>) -> Self {
        chunks.into_iter().next().unwrap_or(0)
    }
}

impl BlobChunk for bool {}
impl Blobbable for bool {
    type Chunk = bool;
    fn to_chunks(&self) -> Vec<Self::Chunk> {
        vec![*self]
    }
    fn from_chunks(chunks: Vec<Self::Chunk>) -> Self {
        chunks.into_iter().next().unwrap_or(false)
    }
}
